server:
  port: 8880
  servlet:
    context-path: /booking

spring:
  datasource:
    url: "jdbc:mysql://localhost:3666/Booking_Online"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

